// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tryTest2Sidebar: [
    {
      type: 'html',
      value: '<div style="margin-bottom: 1rem; border-bottom: 1rem solid #ccc; padding-bottom: 1rem;"><div style="font-weight: bold; color: black; text-align: left; margin-bottom: 0.5rem;">TRY TEST 2</div><div style="font-size: 14px; color: #666; text-align: left; line-height: 1.4;">Brief description of TRY TEST 2</div></div>',
      defaultStyle: true,
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
