// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  __SIDEBAR_ID__: [
    {
      type: 'html',
      value: '<div style="margin-bottom: 1rem; border-bottom: 1px solid #ccc; padding-bottom: 1rem;"><div style="font-weight: bold; color: black; text-align: left; margin-bottom: 0.5rem;">__PROJECT_TITLE__</div><div style="font-size: 14px; color: #666; text-align: left; line-height: 1.4;">__PROJECT_DESCRIPTION__</div></div>',
      defaultStyle: true,
    },
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

export default sidebars;