// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  ubedaMfeSidebar: [
    {
      type: 'html',
      value: '<div style="margin-bottom: 1rem; border-bottom: 1px solid #ccc; padding-bottom: 1rem;"><div style="font-weight: bold; color: black; text-align: left; margin-bottom: 0.5rem;">UBEDA MFE</div><div style="font-size: 14px; color: #666; text-align: left; line-height: 1.4;">A comprehensive documentation project for my awesome application</div></div>',
      defaultStyle: true,
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
